#!/bin/bash

# 多技能仓库匹配测试
# 验证修复后能正确匹配技能

echo "🧪 Testing Multi-Skill Repository Matching Fix"
echo "=============================================="
echo ""

# 测试场景
echo "📋 Test Case: inference-sh-9/skills repository"
echo ""
echo "User clicks: data-visualization"
echo "  - skill.id: 'inference-sh-9/skills'"
echo "  - skill.name: 'data-visualization'"
echo "  - skill.skillId: undefined (fallback to name)"
echo ""
echo "Expected behavior:"
echo "  1. Should match skill with name='data-visualization'"
echo "  2. Cache key: 'inference-sh-9/skills@data-visualization' -> 'inference-sh-9-skills@data-visualization'"
echo "  3. Should open correct SKILL.md file"
echo ""

echo "✅ Fix Summary:"
echo ""
echo "Before Fix:"
echo "  - Used skill.id ('inference-sh-9/skills') to match"
echo "  - No match found, defaulted to first skill"
echo "  - Opened wrong skill (agent-tools)"
echo ""
echo "After Fix:"
echo "  - Use skill.name ('data-visualization') as subSkillName"
echo "  - Match skill by name in the repository"
echo "  - Open correct skill (data-visualization)"
echo ""

echo "🔍 Key Changes:"
echo ""
echo "1. SkillDetailProvider.ts:"
echo "   - Build cache key with sub-skill name"
echo "   - Pass skill.name as fallback for skillId"
echo ""
echo "2. APIClient.fetchRemoteSkillMd():"
echo "   - Accept subSkillName parameter"
echo "   - Use it to match skills in multi-skill repos"
echo ""
echo "3. APIClient.fetchWithClone():"
echo "   - Match by subSkillName first"
echo "   - Fall back to skill.id matching"
echo ""

echo "🚀 Ready to test!"
echo ""
echo "Steps:"
echo "1. Compile: npm run compile ✓"
echo "2. Press F5 to launch extension"
echo "3. Search for 'data-visualization'"
echo "4. Click on the skill"
echo "5. Verify the correct SKILL.md opens"
echo ""
echo "Expected log output:"
echo "  [SkillDetailProvider] Fetching skill: repository=https://github.com/inference-sh-9/skills.git, id=inference-sh-9/skills, subSkill=data-visualization"
echo "  [APIClient] Looking for sub-skill: data-visualization"
echo "  [APIClient] ✓ Selected matching skill: data-visualization"
echo "  [APIClient] Cached to .../skill-cache/inference-sh-9-skills@data-visualization.md"
